# Numpy

NumPy (Numerical Python) is a powerful library in Python used for numerical and mathematical computations. It provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays efficiently. NumPy is a fundamental package for scientific computing with Python and is widely used in various fields such as data analysis, machine learning, statistics, physics, engineering, and more.

Key features and functionalities of NumPy include:

1. **Multi-dimensional Arrays:** NumPy's primary data structure is the `ndarray`, which is an N-dimensional array. It allows you to create arrays of different shapes and sizes, ranging from simple 1D arrays to complex multi-dimensional arrays.

2. **Mathematical Functions:** NumPy provides a wide range of mathematical functions that can be applied to arrays, enabling element-wise operations and broadcasting. These functions include basic arithmetic operations, trigonometric functions, logarithms, exponents, and more.

3. **Array Manipulation:** NumPy offers functions to reshape, transpose, concatenate, and split arrays. You can also extract specific elements or slices from arrays using array indexing and slicing techniques.

4. **Broadcasting:** NumPy allows arrays with different shapes to be operated together. When performing operations between arrays of different shapes, NumPy automatically broadcasts the smaller array to match the shape of the larger one, making element-wise operations convenient.

5. **Linear Algebra:** NumPy provides essential linear algebra operations, such as matrix multiplication, matrix inversion, eigenvalue decomposition, and more.

6. **Random Number Generation:** NumPy has a robust random number generator that can produce random samples from various probability distributions, which is particularly useful in simulations and statistical analysis.

7. **Integration with Other Libraries:** NumPy is a fundamental building block for many other Python libraries used in scientific computing, data analysis, and machine learning, such as SciPy, pandas, and scikit-learn.

Use cases of NumPy:

1. **Data Analysis and Manipulation:** NumPy's array operations and broadcasting capabilities are widely used in data analysis and manipulation tasks. It allows efficient handling and processing of large datasets.

2. **Scientific and Engineering Computations:** NumPy's support for multi-dimensional arrays and mathematical functions makes it a go-to library for scientific and engineering computations, including simulations, signal processing, and image processing.

3. **Machine Learning:** NumPy is heavily used in machine learning algorithms for data preprocessing, feature extraction, and model training due to its efficient array operations and mathematical functions.

4. **Statistical Analysis:** NumPy is instrumental in statistical computations and hypothesis testing, enabling researchers to work with large datasets efficiently.

5. **Visualization:** NumPy arrays can be easily integrated with visualization libraries like Matplotlib for plotting and graphing data.

In summary, NumPy is a crucial library for numerical computing in Python, providing efficient array operations and mathematical functions, making it a versatile tool for a wide range of applications in scientific, engineering, and data-related domains.

## Multi-dimensional Arrays

NumPy provides a wide range of functions related to multi-dimensional arrays. Here are some of the essential functions along with examples:

1. **Creating Arrays:**

- `numpy.array`: Create an array from a Python list or tuple.

```python

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]
```

- `numpy.zeros`: Create an array of zeros with a specified shape.

```python

zeros_arr = np.zeros((2, 3))
print(zeros_arr)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]
```

- `numpy.ones`: Create an array of ones with a specified shape.

```python

ones_arr = np.ones((3, 2))
print(ones_arr)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]
```

- `numpy.arange`: Create an array with evenly spaced values within a given interval.

```python

range_arr = np.arange(1, 6)
print(range_arr)  # Output: [1 2 3 4 5]
```

2. **Array Indexing and Slicing:**

- Accessing elements in a 1D array:

```python

arr = np.array([1, 2, 3, 4, 5])
print(arr[2])      # Output: 3
print(arr[1:4])    # Output: [2 3 4]
```

- Accessing elements in a 2D array:

```python

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])      # Output: 6
print(arr_2d[:, 1])      # Output: [2 5 8]
```

3. **Array Operations:**

- Element-wise addition, subtraction, multiplication, and division:

```python

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add_result = arr1 + arr2    # [5 7 9]
sub_result = arr1 - arr2    # [-3 -3 -3]
mul_result = arr1 * arr2    # [4 10 18]
div_result = arr1 / arr2    # [0.25 0.4  0.5]
```

- Dot product of two arrays (Matrix multiplication):

```python

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(matrix1, matrix2)
print(dot_product)
# Output:
# [[19 22]
#  [43 50]]
```

4. **Array Shape Manipulation:**

- `numpy.reshape`: Reshape an array to a specified shape.

```python

arr = np.arange(1, 10)
reshaped_arr = arr.reshape(3, 3)
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
```

- `numpy.transpose`: Transpose an array (swap rows and columns).

```python

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print(transposed_arr)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]
```

5. **Array Concatenation:**

- `numpy.concatenate`: Concatenate two or more arrays along a specified axis.

```python

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)  # Output: [1 2 3 4 5 6]
```

These are just a few of the many functions available in NumPy for multi-dimensional arrays. NumPy offers a vast array of functionalities to manipulate, reshape, and perform operations on multi-dimensional arrays efficiently.

Here is a comprehensive list of some of the essential functions related to multi-dimensional arrays in NumPy. Keep in mind that NumPy is actively developed, and new functions may have been added since my last update. For the latest and most up-to-date information, please refer to the official NumPy documentation.

1. **Creating Arrays:**

- `numpy.array`: Create an array from a Python list or tuple.
- `numpy.zeros`: Create an array of zeros with a specified shape.
- `numpy.ones`: Create an array of ones with a specified shape.
- `numpy.empty`: Create an array without initializing its elements.
- `numpy.full`: Create an array with a specified value filled in.
- `numpy.eye`: Create a 2D identity matrix.
- `numpy.arange`: Create an array with evenly spaced values within a given interval.
- `numpy.linspace`: Create an array with a specified number of evenly spaced values within a given interval.
- `numpy.meshgrid`: Generate coordinate matrices from coordinate vectors.

2. **Array Indexing and Slicing:**

- Basic indexing: Accessing elements in an array using integer indices.
- Slicing: Extracting specific sections of an array using slices.
- Fancy indexing: Accessing elements in an array using arrays of indices or boolean masks.

3. **Array Operations:**

- Element-wise arithmetic operations: Addition, subtraction, multiplication, division, etc.
- Element-wise mathematical functions: `numpy.sin`, `numpy.cos`, `numpy.exp`, `numpy.sqrt`, etc.
- `numpy.dot`: Dot product of two arrays (Matrix multiplication).
- `numpy.matmul`: Matrix multiplication, handling 2D arrays as matrices.
- `numpy.tensordot`: Compute tensor dot product along specified axes.

4. **Array Shape Manipulation:**

- `numpy.reshape`: Reshape an array to a specified shape.
- `numpy.resize`: Return a new array with a specified size.
- `numpy.transpose`: Transpose an array (swap rows and columns).
- `numpy.swapaxes`: Swap the two specified axes of an array.
- `numpy.flatten`: Flatten an array to a 1D array.
- `numpy.ravel`: Return a flattened 1D array (same as flatten, but may return a view instead of a copy).
- `numpy.squeeze`: Remove single-dimensional entries from the shape of an array.

5. **Array Splitting and Joining:**

- `numpy.split`: Split an array into multiple sub-arrays along a specified axis.
- `numpy.hsplit`: Split an array horizontally (along columns).
- `numpy.vsplit`: Split an array vertically (along rows).
- `numpy.concatenate`: Concatenate two or more arrays along a specified axis.
- `numpy.hstack`: Stack arrays in sequence horizontally (along columns).
- `numpy.vstack`: Stack arrays in sequence vertically (along rows).

6. **Array Iteration:**

- `numpy.nditer`: Efficient multi-dimensional array iteration.

7. **Statistical Functions:**

- `numpy.mean`: Compute the mean along a specified axis.
- `numpy.median`: Compute the median along a specified axis.
- `numpy.sum`: Compute the sum of array elements along a specified axis.
- `numpy.min`: Find the minimum value along a specified axis.
- `numpy.max`: Find the maximum value along a specified axis.
- `numpy.std`: Compute the standard deviation along a specified axis.
- `numpy.var`: Compute the variance along a specified axis.

8. **Linear Algebra Functions:**

- `numpy.linalg.inv`: Compute the (multiplicative) inverse of a matrix.
- `numpy.linalg.det`: Compute the determinant of a matrix.
- `numpy.linalg.eig`: Compute the eigenvalues and right eigenvectors of a square array.
- `numpy.linalg.solve`: Solve a linear matrix equation.

9. **Random Number Generation:**

- `numpy.random.rand`: Generate random numbers from a uniform distribution.
- `numpy.random.randn`: Generate random numbers from a standard normal distribution.
- `numpy.random.randint`: Generate random integers within a specified range.
- `numpy.random.random_sample`: Generate random floats in the half-open interval [0.0, 1.0).

These are some of the most commonly used functions related to multi-dimensional arrays in NumPy. NumPy is a powerful library with a vast collection of functions, and this list is by no means exhaustive. For a complete and detailed reference, please refer to the official NumPy documentation: https://numpy.org/doc/stable/.

## Creating Arrays

Sure! Here are examples for each of the functions related to creating arrays in NumPy:

1. **numpy.array: Create an array from a Python list or tuple.**

```python

import numpy as np

# Creating an array from a Python list
arr_list = np.array([1, 2, 3, 4, 5])
print(arr_list)  # Output: [1 2 3 4 5]

# Creating an array from a Python tuple
arr_tuple = np.array((10, 20, 30, 40, 50))
print(arr_tuple)  # Output: [10 20 30 40 50]
```

2. **numpy.zeros: Create an array of zeros with a specified shape.**

```python

zeros_arr = np.zeros((3, 4))
print(zeros_arr)
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]
```

3. **numpy.ones: Create an array of ones with a specified shape.**

```python

ones_arr = np.ones((2, 3))
print(ones_arr)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]
```

4. **numpy.empty: Create an array without initializing its elements.**

```python

empty_arr = np.empty((2, 2))
print(empty_arr)
# Output: The content of the array may vary, as it is not initialized.
# Example output: 
# [[0. 0.]
#  [0. 0.]]
```

5. **numpy.full: Create an array with a specified value filled in.**

```python

full_arr = np.full((3, 3), 7)
print(full_arr)
# Output:
# [[7 7 7]
#  [7 7 7]
#  [7 7 7]]
```

6. **numpy.eye: Create a 2D identity matrix.**

```python

identity_matrix = np.eye(4)
print(identity_matrix)
# Output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]
```

7. **numpy.arange: Create an array with evenly spaced values within a given interval.**

```python

range_arr = np.arange(10, 20, 2)
print(range_arr)  # Output: [10 12 14 16 18]
```

8. **numpy.linspace: Create an array with a specified number of evenly spaced values within a given interval.**

```python

lin_space = np.linspace(0, 1, 5)
print(lin_space)  # Output: [0.   0.25 0.5  0.75 1.  ]
```

9. **numpy.meshgrid: Generate coordinate matrices from coordinate vectors.**

```python

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
# Output:
# [[1 2 3]
#  [1 2 3]
#  [1 2 3]]

print(Y)
# Output:
# [[4 4 4]
#  [5 5 5]
#  [6 6 6]]
```

In the `meshgrid` example, the function generates coordinate matrices `X` and `Y` from the coordinate vectors `x` and `y`, respectively. It creates a grid of points for all combinations of `x` and `y` values, which is useful for plotting surfaces and evaluating functions on a grid.

### Exercise

Sure! Let's create an exercise covering various questions related to creating NumPy arrays.

Exercise: Creating NumPy Arrays

1. **Create a 1D array**: Create a NumPy array with values [1, 2, 3, 4, 5].

2. **Create a 2D array**: Create a 2D NumPy array with the following matrix:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

3. **Create an array of zeros**: Create a NumPy array of zeros with a shape (3, 4).

4. **Create an array of ones**: Create a NumPy array of ones with a shape (2, 3).

5. **Create an empty array**: Create an empty NumPy array with a shape (2, 2). Print the array, and observe the initial values (which might not be zeros).

6. **Create a full array**: Create a NumPy array of shape (3, 3) with all values initialized to 7.

7. **Create an identity matrix**: Create a 3x3 identity matrix using NumPy.

8. **Create an array using arange**: Create a NumPy array containing even numbers from 2 to 20.

9. **Create an array using linspace**: Create a NumPy array with 5 evenly spaced values between 0 and 1 (inclusive).

10. **Create a meshgrid**: Given two 1D arrays x and y:
```
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
```
Use `numpy.meshgrid` to generate coordinate matrices X and Y.

11. **Create a random array**: Create a 3x3 NumPy array filled with random numbers from a uniform distribution between 0 and 1.

12. **Create a random integer array**: Create a 2x2 NumPy array filled with random integers between 1 and 10.

13. **Create a custom function to initialize an array**: Write a Python function that takes a shape (rows, columns) as input and returns a NumPy array where each element is twice the sum of its row and column indices. For example, for a 3x4 array, the element at (1, 2) should be 2 * (1 + 2) = 6.

14. **Manipulate array shape**: Given a 1D NumPy array `[1, 2, 3, 4, 5, 6]`, reshape it to a 2D array of shape (2, 3).

15. **Split and concatenate arrays**: Given two 1D NumPy arrays `[1, 2, 3]` and `[4, 5, 6]`, concatenate them horizontally and vertically.

16. **Create an array using broadcasting**: Create a NumPy array that adds a constant value of 5 to each element of the array `[1, 2, 3, 4, 5]`.

17. **Create a random 3D array**: Create a 3D NumPy array with shape (2, 3, 4) filled with random numbers from a normal distribution with mean 0 and standard deviation 1.

These exercises cover a range of scenarios where you'll be required to create NumPy arrays using different techniques and functions. Practice these exercises to solidify your understanding of array creation in NumPy.

In [2]:
# Create a 1D array: Create a NumPy array with values [1, 2, 3, 4, 5].
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
# Create a 2D array: Create a 2D NumPy array with the following matrix:

[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Create an array of zeros: Create a NumPy array of zeros with a shape (3, 4).
print(np.zeros((3,4)))
# Create an array of ones: Create a NumPy array of ones with a shape (2, 3).
print('\n',np.ones((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Create an empty array: Create an empty NumPy array with a shape (2, 2). Print the array, and observe the initial values (which might not be zeros).
print(np.empty((2,2)), end ='\n\n')
# Create a full array: Create a NumPy array of shape (3, 3) with all values initialized to 7.
print(np.full((3,3),7), end ='\n\n')
# Create an identity matrix: Create a 3x3 identity matrix using NumPy.
print(np.eye(3), end ='\n\n')
# Create an array using arange: Create a NumPy array containing even numbers from 2 to 20.
print(np.arange(2,21,2), end ='\n\n')
# Create an array using linspace: Create a NumPy array with 5 evenly spaced values between 0 and 1 (inclusive).
print(np.linspace(0,1,5), end ='\n\n')
# Create a meshgrid: Given two 1D arrays x and y:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
X,Y= np.meshgrid(x,y)
print(X, end ='\n\n')
print(Y, end ='\n\n')

[[0. 0.]
 [0. 0.]]

[[7 7 7]
 [7 7 7]
 [7 7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 2  4  6  8 10 12 14 16 18 20]

[0.   0.25 0.5  0.75 1.  ]

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[4 4 4]
 [5 5 5]
 [6 6 6]]



In [8]:
# Create a random array: Create a 3x3 NumPy array filled with random numbers from a uniform distribution between 0 and 1.
print(np.random.rand(3,3),end='\n\n')
# Create a random integer array: Create a 2x2 NumPy array filled with random integers between 1 and 10.
print(np.random.randint(1,10,(2,2)),end='\n\n')




[[0.77786904 0.2185969  0.19735923]
 [0.93720954 0.44545583 0.75838172]
 [0.56816626 0.81986997 0.6689524 ]]

[[1 5]
 [2 1]]



In [9]:
# Create a custom function to initialize an array: Write a Python function that takes a shape (rows, columns) as input and returns a NumPy array where each element is twice the sum of its row and column indices. For example, for a 3x4 array, the element at (1, 2) should be 2 * (1 + 2) = 6.
def fun(row,col):
    res = np.zeros((row,col))
    for i in range(row):
        for j in range(col):
            res[i][j] = 2*(i+1+j+1)
    return res
print(fun(3,4))
            

[[ 4.  6.  8. 10.]
 [ 6.  8. 10. 12.]
 [ 8. 10. 12. 14.]]


In [10]:
# Manipulate array shape: Given a 1D NumPy array [1, 2, 3, 4, 5, 6], reshape it to a 2D array of shape (2, 3).
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape((2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Split and concatenate arrays: Given two 1D NumPy arrays [1, 2, 3] and [4, 5, 6], concatenate them horizontally and vertically.

arr1 = np.array([[1,2,3,6],[6,7,3,4],[8,6,5,90]])
arr2 = np.array([4,5,6,90])
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.split(arr2,4),'\n')
print(np.vsplit(arr1,3),'\n')
print(np.vstack((arr1,arr2)),'\n')
print(np.hstack((x,y)))

[array([4]), array([5]), array([6]), array([90])] 

[array([[1, 2, 3, 6]]), array([[6, 7, 3, 4]]), array([[ 8,  6,  5, 90]])] 

[[ 1  2  3  6]
 [ 6  7  3  4]
 [ 8  6  5 90]
 [ 4  5  6 90]] 

[1 2 3 4 5 6]


In [12]:
# Create an array using broadcasting: Create a NumPy array that adds a constant value of 5 to each element of the array [1, 2, 3, 4, 5].
np.array([1,2,3,4,5])+5

array([ 6,  7,  8,  9, 10])

In [13]:
# Create a random 3D array: Create a 3D NumPy array with shape (2, 3, 4) filled with random numbers from a normal distribution with mean 0 and standard deviation 1.
np.random.normal(0,1 , size =(2,3,4))

array([[[ 0.1885662 ,  1.04485813, -0.55407911, -0.99088303],
        [ 0.87889052, -0.5802316 , -0.82559506,  0.34705097],
        [-1.74174254, -2.96054459, -1.07406092, -0.25515533]],

       [[-0.52378059, -1.9040345 , -0.32307583, -0.14475769],
        [-1.66977936, -0.32037339, -1.42118339,  0.39462212],
        [-0.30205318, -0.43750811, -1.54267981, -0.7156507 ]]])

## Exercise on array indexing and sclicing

Here's an exercise on Array Indexing and Slicing with 7 questions:

1. Given the NumPy array `arr = np.array([10, 20, 30, 40, 50])`, extract and print the element at index 2.

2. Given the NumPy array `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`, use slicing to extract and print the subarray from index 2 to index 6 (inclusive).

3. Given the 2D NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, print the element at row index 1 and column index 2.

4. Given the 2D NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, use slicing to extract and print the subarray corresponding to the last two rows.

5. Given the 2D NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, use slicing to extract and print the subarray corresponding to the first two columns.

6. Given the 2D NumPy array `arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, use slicing to extract and print the subarray corresponding to the center 2x2 submatrix `[ [5, 6], [8, 9] ]`.

7. Given the 1D NumPy array `arr = np.array([1, 2, 3, 4, 5])`, use array indexing and slicing to replace the elements at indices 2 and 4 with new values 10 and 20, respectively.

Remember to import NumPy (`import numpy as np`) before attempting the exercise. This exercise will help you practice indexing and slicing arrays in NumPy, which are fundamental operations for data manipulation and analysis.

In [14]:
# Given the NumPy array arr = np.array([10, 20, 30, 40, 50]), extract and print the element at index 2.
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [15]:
# Given the NumPy array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), use slicing to extract and print the subarray from index 2 to index 6 (inclusive).
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[2:7]

array([3, 4, 5, 6, 7])

In [16]:
# Given the 2D NumPy array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), print the element at row index 1 and column index 2.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[1,2]

6

In [17]:
# Given the 2D NumPy array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), use slicing to extract and print the subarray corresponding to the last two rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
# Given the 2D NumPy array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), use slicing to extract and print the subarray corresponding to the first two columns.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
# Given the 2D NumPy array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), use slicing to extract and print the subarray corresponding to the center 2x2 submatrix [ [5, 6], [8, 9] ].
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [20]:
# Given the 1D NumPy array arr = np.array([1, 2, 3, 4, 5]), use array indexing and slicing to replace the elements at indices 2 and 4 with new values 10 and 20, respectively.
arr = np.array([1, 2, 3, 4, 5])
arr[1],arr[3]=10,20
arr

array([ 1, 10,  3, 20,  5])

## Exercise on Array operations

Here's an exercise on Array Operations:

1. Create two 1D NumPy arrays:
   - `arr1 = np.array([1, 2, 3, 4, 5])`
   - `arr2 = np.array([6, 7, 8, 9, 10])`

2. Perform element-wise addition of `arr1` and `arr2` and store the result in a new array `sum_array`.

3. Perform element-wise subtraction of `arr2` from `arr1` and store the result in a new array `diff_array`.

4. Calculate the dot product of `arr1` and `arr2` and store the result in a variable `dot_product`.

5. Create a 2D NumPy array:
   ```
   arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
   ```

6. Calculate the sum of all elements in `arr_2d` and store it in a variable `total_sum`.

7. Calculate the sum of elements along each column of `arr_2d` and store the result in an array `col_sum`.

8. Calculate the product of elements along each row of `arr_2d` and store the result in an array `row_product`.

9. Reshape `arr1` to a 2D array of shape (1, 5) and store it in a new variable `arr1_2d`.

10. Transpose `arr_2d` and store it in a new variable `arr_2d_transposed`.

11. Calculate the mean value of `arr1` and store it in a variable `mean_value`.

12. Find the minimum and maximum values in `arr2` and store them in variables `min_value` and `max_value`, respectively.

13. Find the indices of all elements greater than 5 in `arr1` and store them in an array `indices_greater_than_5`.

14. Sort `arr2` in ascending order and store the sorted array in a new variable `sorted_arr2`.

15. Create a boolean mask for elements in `arr1` that are divisible by 2 and store it in a variable `mask_divisible_by_2`.

16. Use the boolean mask to extract the elements from `arr1` that are divisible by 2 and store them in a new array `elements_divisible_by_2`.

This exercise covers various array operations in NumPy, including element-wise operations, dot product, sum, product, reshape, transpose, mean, minimum, maximum, sorting, and boolean masking. It will help you practice different array operations and improve your familiarity with NumPy functions.

In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [22]:
# Perform element-wise addition of arr1 and arr2 and store the result in a new array sum_array.
sum_array = arr1+arr2

In [23]:
# Perform element-wise subtraction of arr2 from arr1 and store the result in a new array diff_array.
diff_array = arr1-arr2

In [24]:
# Calculate the dot product of arr1 and arr2 and store the result in a variable dot_product.
dot_product = np.dot(arr1,arr2)

In [25]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
# Calculate the sum of all elements in arr_2d and store it in a variable total_sum.
total_sum = np.sum(arr_2d)
total_sum

45

In [27]:
# Calculate the sum of elements along each column of arr_2d and store the result in an array col_sum.
col_sum = np.sum(arr_2d,axis = 0)
col_sum

array([12, 15, 18])

In [28]:
# Calculate the product of elements along each row of arr_2d and store the result in an array row_product.
row_product = np.prod(arr_2d,axis =1)
row_product

array([  6, 120, 504])

In [29]:
# Reshape arr1 to a 2D array of shape (1, 5) and store it in a new variable arr1_2d.

arr1_2d = arr1.reshape((1,5))
arr1_2d

array([[1, 2, 3, 4, 5]])

In [30]:
# Transpose arr_2d and store it in a new variable arr_2d_transposed.
arr_2d_transposed = np.transpose(arr_2d)
arr_2d_transposed

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
# Calculate the mean value of arr1 and store it in a variable mean_value.
mean_value = arr1.mean()
mean_value

3.0

In [32]:
# Find the minimum and maximum values in arr2 and store them in variables min_value and max_value, respectively.
min_value,max_value = arr2.min(),arr2.max()
print(min_value,max_value)

6 10


In [33]:
# Find the indices of all elements greater than 5 in arr1 and store them in an array indices_greater_than_5.
indices_greater_than_5 = np.where(arr1>5)[0]
indices_greater_than_5

array([], dtype=int64)

In [34]:
# Sort arr2 in ascending order and store the sorted array in a new variable sorted_arr2.
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([ 6,  7,  8,  9, 10])

In [35]:
# Create a boolean mask for elements in arr1 that are divisible by 2 and store it in a variable mask_divisible_by_2.
mask_divisible_by_2 = arr1%2==0
mask_divisible_by_2

array([False,  True, False,  True, False])

In [36]:
# Use the boolean mask to extract the elements from arr1 that are divisible by 2 and store them in a new array elements_divisible_by_2.

elements_divisible_by_2 = arr1[mask_divisible_by_2]
elements_divisible_by_2

array([2, 4])

## Exercise on Array Shape Manipulation

Consider the following NumPy array representing a 3x4 matrix:

Original 3x4 matrix


original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])
                           
                    
Perform the following operations on the original_array and answer the questions accordingly:

Reshape the original_array into a 2x6 matrix.

Resize the original_array to a 2x2 matrix.

Transpose the original_array.

Swap the axes of the original_array.

Flatten the original_array into a 1D array.

Ravel the original_array into a 1D array.

Squeeze the original_array to remove any single-dimensional entries.

In [37]:
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [38]:
# Reshape the original_array into a 2x6 matrix.
np.reshape(original_array,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [39]:
# Resize the original_array to a 2x2 matrix.
np.resize(original_array,(2,2))

array([[1, 2],
       [3, 4]])

In [40]:
# Transpose the original_array.
np.transpose(original_array)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [51]:
# Swap the axes of the original_array
np.swapaxes(original_array,0,1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [58]:
# Flatten the original_array into a 1D array.
original_array.flatten()




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
# Ravel the original_array into a 1D array.
np.ravel(original_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
# Squeeze the original_array to remove any single-dimensional entries.
np.squeeze(original_array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Numpy.nditer

`numpy.nditer` is a powerful function in NumPy that provides an iterator object to efficiently loop over arrays. It's particularly useful when you want to perform element-wise operations on arrays. Here's an example using `numpy.nditer`:

Example:

```python
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Using nditer to loop through the array
print("Original array:")
print(arr)

print("\nSquared array:")
# Create a new empty array to store squared values
squared_arr = np.empty_like(arr)

# Loop through the array and calculate the square of each element
with np.nditer([arr, squared_arr], op_flags=['readwrite']) as it:
    for x, y in it:
        y[...] = x ** 2

print(squared_arr)
```

Output:

```
Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Squared array:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
```

Exercise question:

Write a function that takes two input arrays, `arr1` and `arr2`, and returns a new array that contains the element-wise multiplication of the two arrays. Use `numpy.nditer` to implement the function efficiently.

Example function signature:
```python
def element_wise_multiply(arr1, arr2):
    # Your implementation using numpy.nditer
    pass
```

For instance, if you pass `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])`, the function should return `np.array([4, 10, 18])`, which is the result of element-wise multiplication of the two arrays.

In [8]:
import numpy as np
def fun(arr1,arr2):
    res = np.array([], dtype = int)
    with np.nditer([arr1,arr2],op_flags=['readwrite']) as it:
        for x,y in it:
            res= np.append(res,x*y)
    return res
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(
    fun(arr1,arr2))


[ 4 10 18]
